### ISSUE TITLE
TeXLive 2019: LaTeX build fails when using `minted` package due to `pygmentize`

### ISSUE THREAD

**Issue by stephanlukasczyk** [sumanstats/TeXLive#1]
I encountered the following problem, when using your texlive-2019 image in GitLab CI: I tried to compile a document that uses the `minted` package, which failed due to a not found installation of `pygmentize`. My `.gitlab-ci.yml` was:
```
image: sumankhanal/texlive-2019
before_script:
  - tlmgr update --self --all
build:
  - script:
    - latexmk -pdf test.tex
  artifacts:
    paths:
      - test.tex
```
A MWE LaTeX file is
```latex
\documentclass{article}
\usepackage{minted}
\begin{document}
\mintinline{java}{public static void main(String[] args)}
\end{document}
```
and I also provided a `.latexmkrc` in the project:
```perl
$pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 --shell-escape %O %S';
```
I was able to fix this by adding the following line to the `before_script` section of the `.gitlab-ci.yml`:
```
  - apt-get update && apt-get install -y python3-pygments && rm -rf /var/lib/apt/lists/*
```
I am not sure, whether this is a fault on my side or whether there is now some dependency on Python 3 in `minted`, since the package install also installed Python 3.7 as a dependency. If it's due to `minted`, could you please update the container definition such that it installs the `pygments` library for both Python versions?
